cdcservice:
  build: ./eventuate-local-java-cdc-service
  ports:
    - "8099:8080"
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
    SPRING_DATASOURCE_USERNAME: eventuate
    SPRING_DATASOURCE_PASSWORD: eventuate
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_POLLING_REQUEST_PERIOD_IN_MILLISECONDS: 4000
    SPRING_PROFILES_ACTIVE: EventuatePolling