zookeeper:
  image: debezium/zookeeper:0.2
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka:
  image: debezium/kafka:0.2
  ports:
    - 9092:9092
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
  links:
    - zookeeper

mysql:
  image: mysql:5.7.13
  ports:
    - 3306:3306
  volumes:
    - ./mysql.conf.d:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

