cdcservice:
  build: ./new-cdc/eventuate-local-java-cdc-sql-service
  ports:
    - "8099:8080"
  links:
    - mysqlbinlogpipeline
    - postgrespollingpipeline
    - postgreswalpipeline
    - kafka
    - zookeeper
  environment:
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATE_CDC_READER_READER1_TYPE: mysql-binlog
    EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:mysql://mysqlbinlogpipeline:3306/eventuate
    EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: mysqluser
    EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: mysqlpw
    EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
    EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/1
    EVENTUATE_CDC_READER_READER1_CDCDBUSERNAME: root
    EVENTUATE_CDC_READER_READER1_CDCDBPASSWORD: rootpassword
    EVENTUATE_CDC_READER_READER1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
    EVENTUATE_CDC_READER_READER1_MYSQLBINLOGCLIENTUNIQUEID: 1234567890
    EVENTUATE_CDC_READER_READER1_OFFSETSTOREKEY: MySqlBinlog

    EVENTUATE_CDC_READER_READER2_TYPE: polling
    EVENTUATE_CDC_READER_READER2_DATASOURCEURL: jdbc:postgresql://postgreswalpipeline/eventuate
    EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME: eventuate
    EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD: eventuate
    EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
    EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/2

    EVENTUATE_CDC_READER_READER3_TYPE: postgres-wal
    EVENTUATE_CDC_READER_READER3_DATASOURCEURL: jdbc:postgresql://postgrespollingpipeline/eventuate
    EVENTUATE_CDC_READER_READER3_DATASOURCEUSERNAME: eventuate
    EVENTUATE_CDC_READER_READER3_DATASOURCEPASSWORD: eventuate
    EVENTUATE_CDC_READER_READER3_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
    EVENTUATE_CDC_READER_READER3_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/3

    EVENTUATE_CDC_PIPELINE_1_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_1_READER: Reader1

    EVENTUATE_CDC_PIPELINE_2_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_2_READER: Reader2

    EVENTUATE_CDC_PIPELINE_3_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_3_READER: Reader3
