version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-mysql-common.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-postgres-wal:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-postgres-wal.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-mysql-embedded-cdc:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-mysql-embedded-cdc.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-mysql-cdc-connector-polling:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-mysql-cdc-connector-polling.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-mysql-cdc-connector-mysql-binlog:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-mysql-cdc-connector-mysql-binlog.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-cdc-mysql:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-all-cdc-mysql.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-new-cdc-mysql:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-all-new-cdc-mysql.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-new-cdc-postgres-polling:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-all-new-cdc-postgres-polling.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-new-cdc-postgres-wal:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-all-new-cdc-postgres-wal.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build-new-cdc-unified:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./scripts/build-and-test-all-new-cdc-unified.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  publish:
    machine: true
    working_directory: ~/eventuate-local-java
    steps:
      - checkout
      - restore_cache:
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-local-java-{{ checksum "build.gradle" }}
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./scripts/deploy-artifacts.sh
          when: on_success
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - build-mysql-embedded-cdc:
          requires:
            - build
      - build-postgres-wal:
          requires:
            - build
      - build-mysql-cdc-connector-polling:
          requires:
            - build
      - build-mysql-cdc-connector-mysql-binlog:
          requires:
            - build
      - build-cdc-mysql:
          requires:
            - build-mysql-embedded-cdc
      - build-new-cdc-mysql:
          requires:
            - build-mysql-cdc-connector-mysql-binlog
      - build-new-cdc-postgres-wal:
          requires:
            - build-postgres-wal
      - build-new-cdc-postgres-polling:
          requires:
            - build-mysql-cdc-connector-polling
      - build-new-cdc-unified:
          requires:
            - build-postgres-wal
      - publish:
          requires:
            - build-postgres-wal
            - build-cdc-mysql
            - build-new-cdc-mysql
            - build-new-cdc-postgres-wal
            - build-new-cdc-postgres-polling
            - build-new-cdc-unified
